# Файл настроек для работы в БОЕВОМ окружении

debug: true

db.options:
  driver: 'pdo_mysql'
  host: 'localhost'
  dbname: 'b24p'
  user: 'b24p'
  password: ''

сhat.api:
  webhookUrl: ""
  apiUrl: ""
  token: ""

bot:
  secret: ""

monolog.logfile: "../log/logfile.txt"
monolog.level: "DEBUG"