# Файл настроек для работы в тестовом окружении

debug: true

db.options:
  driver: ''
  host: ''
  dbname: ''
  user: ''
  password: ''

chat.api:
  webhookUrl: ""
  apiUrl: ""
  token: ""

  bot:
    secret: ""

monolog.logfile: "../log/logfile.txt"
monolog.level: "DEBUG"